# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.warning.mode=none

# Project
project_name=ExampleMod

# Mod
mod_id=example_mod
mod_version=0.0.1-SNAPSHOT
mod_maven_group=com.example.example_mod
mod_archives_base_name=ExampleMod
mod_name=Example Mod
mod_description=Example mod description.\nSupports multilines.
mod_author=Example Author
mod_homepage_url=https://www.curseforge.com/minecraft/mc-mods/example-mod
mod_issues_url=https://github.com/example-author/example-mod/issues
mod_source_url=https://github.com/example-author/example-mod
mod_license=All Rights Reserved

# Java
java_version=21

# Minecraft
minecraft_version=1.21.5
minecraft_version_range=[1.21.5,1.22)
