## Gradle

# Gradle properties configure Gradle itself and usually have the name 'org.gradle.*'.
# Gradle properties should not be used in build logic, their values should not be
# read/retrieved in build scripts.
# See more information here: https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties

# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
# See more information here: https://docs.gradle.org/current/userguide/config_gradle.html#sec:configuring_jvm_memory
org.gradle.jvmargs=-Xmx3G

# When set to 'true' the Gradle Daemon is used to run the build.
# See more information here: https://docs.gradle.org/current/userguide/gradle_daemon.html#gradle_daemon
org.gradle.daemon=false

# When set to 'all', 'summary', or 'none', Gradle will use different warning type display.
# See more information here: https://docs.gradle.org/current/userguide/command_line_interface.html#sec:command_line_logging
#org.gradle.warning.mode=none

## Project

# The name of the Gradle root project.
# NOTE: This name refers only to Gradle and/or IDE and does not affect the mod itself.
# NOTE: This should match the folder name of the project, or else IDEA may complain (see https://youtrack.jetbrains.com/issue/IDEA-317606).
# We prefer pascal case here.
project_name=ExampleMod

## Mod

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex '[a-z][a-z0-9_]{1,63}'.
# We prefer lower case here (without non-letter symbols, such as "_").
mod_id=examplemod

# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
# This should match the base package used for the mod sources.
# See more information here: https://maven.apache.org/guides/mini/guide-naming-conventions.html
# We prefer lower case here (without non-letter symbols, such as "_").
mod_group_id=com.example.examplemod

# The version number of the mod.
# See more information here: https://semver.org
mod_version=0.0.1-SNAPSHOT

# The base name for the mod artifacts. This will be used for naming the mod JAR files.
# We prefer pascal case here.
mod_archives_base_name=ExampleMod

# The human-readable display name for the mod.
# This simple text is used for display purposes in the mod UI.
mod_name=Example Mod

# The description text for the mod (multiline).
# This simple multiline text is used for display purposes in the mod UI.
# You can leave this field empty.
mod_description=Example mod description.\nSupports multilines.

# The author (or several authors separated by ',') of the mod.
# This simple text is used for display purposes in the mod UI.
mod_authors=Example Author, Another Example Author

# The creator (or several creators separated by ',') who contributed to the mod.
# This simple text is used for display purposes in the mod UI.
# You can leave this field empty.
mod_credits=

# A URL for the 'homepage' for this mod, displayed in the mod UI.
# For example, you can specify here a link to a web page where you can download your mod
# and/or find out more information about it.
# You can leave this field empty.
mod_homepage_url=https://www.curseforge.com/minecraft/mc-mods/example-mod

# A URL for the source code for this mod.
# For example, you can specify here a link to your GitHub/GitLub open source repository, etc.
# You can leave this field empty.
mod_source_url=https://github.com/example-author/example-mod

# A URL to refer people to when problems occur with this mod.
# For example, you can specify here a link to your GitHub/GitLub Issues, etc.
# You can leave this field empty.
mod_issues_url=https://github.com/example-author/example-mod/issues

# A URL to query for updates for this mod.
# See more information here: https://docs.minecraftforge.net/en/latest/misc/updatechecker
# NOTE: This property is Forge-specific.
# You can leave this field empty.
mod_updates_url=

# A file name (in the root of the mod JAR) containing a logo for display.
mod_logo=logo.png

# The license for your mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com. All rights reserved is the default copyright stance, and is thus the default here.
mod_license=All Rights Reserved

## Java

# The version number of Java that must be installed for your mod to work correctly.
# IMPORTANT NOTE: Mojang ships Java 21 to end users in 1.20.5+, so your mod should target Java 21.
java_version=21

## Minecraft

# The version number of Minecraft.
minecraft_version=1.21.5

# The Minecraft version range can use any release version of Minecraft as bounds.
# Snapshots, pre-releases, and release candidates are not guaranteed to sort properly
# as they do not follow standard versioning conventions.
minecraft_version_range=[1.21.5,1.22)

## Forge

# The Forge version must agree with the Minecraft version to get a valid artifact.
forge_version=55.0.16

# The Forge version range can use any version of Forge as bounds or match the loader version range.
forge_version_range=[55.0.16,)

# The loader version range can only use the major version of Forge/FML as bounds.
forge_loader_version_range=[55,)

# The version number of the Forge Gradle plugin.
forge_gradle_version=6.+

## Mixin

# The version of the Sponge Powered Mixin.
mixin_version=0.8.5

# The version of the Sponge Powered Mixin Gradle plugin.
mixin_gradle_version=0.7-SNAPSHOT

## Parchment

# The mappings channel used by Parchment.
parchment_channel=parchment

# The version of the Parchment mappings.
# See all available versions here: https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_version=2025.04.19-1.21.5

# The version of the Parchment Gradle plugin.
parchment_gradle_version=1.+
